import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';
import ReduxQueryProvider from '@/providers/redux-query-provider';
import ModalProvider from '@/providers/modal-provider';
import { cn } from '@/lib/utils';
import SocketProvider from '@/providers/socket-provider';
import ReactQueryProvider from '@/providers/react-query-provider';

const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={cn(font.className, 'bg-white dark:bg-[#313338]')}>
          <ThemeProvider
            attribute='class'
            defaultTheme='dark'
            enableSystem={false}
            storageKey='discord-theme'
          >
            <ReduxQueryProvider>
              <SocketProvider>
                <ReactQueryProvider>
                  <ModalProvider />
                  {children}
                </ReactQueryProvider>
              </SocketProvider>
            </ReduxQueryProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
